"""Initialization for the NPK dynamics of crop
"""

from model_engine.models.wofost.crop_tensorbatch.nutrients.tensor_batch_npk_stress import NPK_Stress_TensorBatch
from model_engine.models.wofost.crop_tensorbatch.nutrients.tensor_batch_npk_demand_uptake import NPK_Demand_Uptake_TensorBatch
from model_engine.models.wofost.crop_tensorbatch.nutrients.tensor_batch_npk_translocation import NPK_Translocation_TensorBatch
